name: 'logistics'
version: '1.0.0'
config-version: 2

profile: 'logistics' # This connects to profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

models:
  logistics:
    # Materialize everything as a table (creates actual tables in Postgres)
    +materialized: table